---

- name: Perforc Key
  command: rpm --import https://package.perforce.com/perforce.pubkey

- name: Perforce Repository
  yum_repository: 
    name: Perforce
    gpgcheck: yes
    baseurl: http://package.perforce.com/yum/rhel/{{ ansible_distribution_major_version }}/x86_64
    enabled: yes
    state: present

- name: Perforce Install
  yum: name=helix-cli update_cache=yes state=present
